### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by tsur** [adamschwartz/chrome-tabs#11]
Hi, really cool what you've done!

I was wondering why using svg instead of just css for the tab shape? I'm not an expert in CSS, but I think it's accomplishable with CSS too. Anyhow, there's maybe no special reason for using svg, but just got curious about it.

Thanks!

**Comment by adamschwartz** [comment]
Thanks @Tsur! I believe a similar shape can be achieved by layering DOM elements with `border-radius` and `transform: skew(...)` but I decided to take this approach because it seemed more straight-forward to me. If there’s an easy way to do it with CSS that you know of, I’d love to see! So please let me know. :)
