### ISSUE TITLE
when you drag a tab, other tab went wrong

### ISSUE THREAD

**Issue by zhenizhui** [adamschwartz/chrome-tabs#16]
![gif](https://cloud.githubusercontent.com/assets/13503884/19505114/5992f1f2-95f2-11e6-8e9f-94f03930cee7.gif)

**Comment by Sjael** [comment]
I noticed this too. It happens when you click and drag a tab that is not already selected. This is because another tab is selected on 'click' not on 'clickdown', which it should be since Chrome is that way. I think the issue seems to be here https://github.com/adamschwartz/chrome-tabs/blob/gh-pages/js/chrome-tabs.js#L162, on line 162.

**Comment by tomerlieber** [comment]
I changed the click event to mouse down event (on line 162) as you said, but it still doesn't behave good.
Any idea?
