### ISSUE TITLE
Contextmenu support

### ISSUE THREAD

**Issue by burtonator** [adamschwartz/chrome-tabs#40]
Does it work with the contextmenu?  That would nail it for me!

**Comment by adamschwartz** [comment]
Can you clarify what you mean by "work with"?

**Comment by burtonator** [comment]
I have the following options when I right click tabs on Chrome:

![image](https://user-images.githubusercontent.com/45447/44871746-94456a00-ac48-11e8-8074-204dd711a851.png)

Would be good to have these here too!

**Comment by burtonator** [comment]
I think mute site and bookmark all tabs might not make sense for a basic impl though.

**Comment by adamschwartz** [comment]
AFAIA, there’s nothing about the current design which would limit an implementer’s ability to augment this project with a contextmenu. In order to keep this project small and manageable, I would prefer to implement it as a separate project. Perhaps __adamschwartz/chrome-tabs-contextmenu__ down the line. But for now, I’m going to close this is as being out-of-scope for this project, which is focused purely on the tabs implementation. Thanks very much for the suggestion though! Please let me know if you ever implement it yourself, and I can link to your project in the README, etc.

**Comment by burtonator** [comment]
We're probably going to use your tabs here:

https://github.com/burtonator/polar-bookshelf
